import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-6 bg-slate-800 text-white border-b-2 shadow-lg">
          <h3 className="font-semibold text-lg">Medium</h3>
        </div>
        {children}
      </body>
    </html>
  );
}
